---
name: dev
path: /Users/sandervandenhaute/Documents/geometry/nmf/data/
log:
  - time
  - objective
  - error
  - iteration
  - L1_H
r: 8
verbose: 20
iters: 3000
eps: 0
delay: 10
eta: 0
beta: 0.1
...
