---
name: dev
path: /Users/sandervandenhaute/Documents/geometry/nmf/data/
log:
  - time
  - objective
  - error
  - iteration
r: 5
verbose: 20
iters: 1000
eps: 0
delay: 10
#eta: 0
#beta: 0.1
alpha: 1
sparsity: 0.9
mu: 0.1
...
