---
name: dev
#solver: anls_bpp
path: /Users/sandervandenhaute/Documents/geometry/nmf/data/
#dirs:
#    - ENSTDkAm
log:
  - time
  - objective
  - error
r: 8
verbose: True
iters: 100
eps: 0
delay: 10
# when running anls_bpp_sparse, beta and eta are parameters
eta: 0
beta: 0.1
...
