---
name: dev
#solver: anls_bpp
path: /Users/sandervandenhaute/Documents/geometry/nmf/data/
#dirs:
#    - ENSTDkAm
r: 8
verbose: True
iters: 1000
nnls_iters: 10
eps: 0
delay: 10
logger:
    - objective
    - l2
...
