---
name: dev
solver: hals
use_new: False
path: /Users/sandervandenhaute/Documents/geometry/nmf/data/
#dirs:
#    - ENSTDkAm
dataset: 'face'
dataset_r: 'full'
verbose: True
n: 800
m: 600
r: 8
iters: 10000
nnls_iters: 10
eps: 0
delay: 10
...
